#!/usr/bin/env bash

#Install Google Chrome
sudo dnf install fedora-workstation-repositories
sudo dnf config-manager setopt google-chrome.enabled=1
sudo dnf config-manager --set-enabled google-chrome -y

# Setup GitHub ssh
sudo dnf install git -y
ssh-keygen -t ed25519 -C "iam-arnab@outlook.com"
echo "When you're prompted to "Enter a file in which to save the key", \nyou can press Enter to accept the default file location. \nPlease note that if you created SSH keys previously, \nssh-keygen may ask you to rewrite another key, in which case we recommend creating a custom-named SSH key. \nTo do so, type the default file location and replace id_ALGORITHM with your custom key name."
echo "\nDo not enter Passphrase and just press enter"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519
cat ~/.ssh/id_ed25519.pub
echo "Follow this: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account"

# Install Node.js with fnm
curl -o- https://fnm.vercel.app/install | bash
fnm install 22
node -v
npm -v

# Install pnpm
npm install -g pnpm@latest-10

# Install Bun
curl -fsSL https://bun.sh/install | bash

# Setup C and C++
sudo dnf install gcc clang gcc-c++ -y

# Setup Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Setup Zig
sudo dnf install zig -y

# Setup snap
sudo dnf install snapd -y
sudo snap install hello-world

# Install Pieces
sudo snap install pieces-for-developers

# Install uv
curl -LsSf https://astral.sh/uv/install.sh | sh

# Install neovim
sudo dnf install neovim -y

# Install bat, eza, zoxide and starship, stow, rg, fd, television
sudo dnf install bat eza stow ripgrep fd-find -y
cargo install --locked television
curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
curl -sS https://starship.rs/install.sh | sh

# Setup lazyvim
git clone https://github.com/LazyVim/starter ~/.config/nvim
rm -rf ~/.config/nvim/.git

# Get dotfiles
cd ~/
git clone git@github.com:zytact/dotfiles.git
cd dotfiles
stow lazyvim
cp mcphub/servers.json ~/.config/mcphub/
stow git
stow npm
stow starship
stow zed

# Setup Japanese
sudo dnf install glibc-langpack-ja
locale -a | grep -i ja_jp.utf8
sudo dnf install google-noto-cjk-fonts
mkdir -p ~/.config/fontconfig/conf.d
wget -P ~/.config/fontconfig/conf.d https://raw.githubusercontent.com/zytact/dotfiles/refs/heads/main/japanese/99-japanese-fonts.conf
fc-cache -fv
