#!/bin/sh

launch_browser()
{
    xdg-open "https://www.oxfordlearnersdictionaries.com/definition/american_english/""$1"
    xdg-open "https://www.oxfordlearnersdictionaries.com/definition/english/""$1"
}

word=$(yad --title "Search" --entry --text "Type word to search: " --geometry=400x100+750+500) || exit 1
launch_browser "$word"