#!/usr/bin/env bash

declare -a subreddit_list=(
    "r/anime"
    "r/animepiracy"
    "r/emacs"
    "r/linux"
    "r/commandline"
    "r/unixporn"
    "r/firefox"
    "r/brave_browser"
    "r/signal"
    "r/kpopfap"
    "r/jisoo"
)

subreddit=$(printf "%s\n" "${subreddit_list[@]}" | rofi -dmenu -i -l 20 -p "Choose Subreddit") || exit 1

post=$(reddio p -f '$num. $title $id$nl' -l 20 "$subreddit" | rofi -dmenu -i -l 20 -p "Last 20 posts on ""$subreddit")

choice=$(printf "Url\nSummary" | rofi -dmenu -i -l 2 -p "Choose what to do")

post_id=$(echo $post | awk '{print $NF}')
URL=$(reddio print -f '$url' by_id/"$post_id")

if [ $choice == "Url" ]; then
    xdg-open "$URL" &
else
    reddio print -f 'TITLE: $title$nl SUBMITTED: $created_pretty AUTHOR: $author$nl URL: $url$nl$nl$text' by_id/"$post_id" | zenity --text-info --height=600 --width=600 &
fi
