#!/usr/bin/env bash

sudo dnf upgrade -y
flatpak update -y
sudo snap refresh
npm -g update
pnpm self-update
pnpm -g update
bun upgrade
bun -g update
rustup update
cargo update
uv self update
cd ~/Projects/ghostty
git pull
zig build -p $HOME/.local -Doptimize=ReleaseFast
cd ~/
