#!/usr/bin/python3

import sys
import subprocess
import os

args = sys.argv
args.pop(0)

for i in range(len(args)):
    args[i] = "file '" + args[i] + "'\n"


with open("files.txt", "w") as file:
    file.writelines(args)

ffmpeg = subprocess.run(
    "ffmpeg -f concat -safe 0 -i files.txt -c copy output.mp4", capture_output=True, check=True, shell=True)

print(ffmpeg.stdout)
print(ffmpeg.stderr)

os.remove("files.txt")
