#!/usr/bin/env bash

declare -A options=(
    [Brave]=https://search.brave.com/search?q=
    [Google]=https://www.google.com/search?q=
    [DuckDuckGo]=https://duckduckgo.com/?q=
    [YouTube]=https://www.youtube.com/results?search_query=
    [Goodreads]=https://www.goodreads.com/search?q=
    [GitHub]=https://github.com/search?q=
    [Wikidata]=https://www.wikidata.org/w/index.php?search=
    [Wikipedia]=https://en.wikipedia.org/w/index.php?search=
    [Z-Library]=https://1lib.in/s/
    [Wallpaperflare]=https://www.wallpaperflare.com/search?wallpaper=
    [Snapcraft]=https://snapcraft.io/search?q=
    [Flathub]=https://flathub.org/apps/search/
    [Merriam Webster]=https://www.merriam-webster.com/dictionary/
    [Fdroid]=https://search.f-droid.org/?q=
    [Wiby.me]=https://wiby.me/?q=
    [DevianArt]=https://www.deviantart.com/search?q=
    [MyAnimeList]=https://myanimelist.net/search/all?q=
)

choice=$(printf "%s\n" "${!options[@]}" | rofi -dmenu -i -l 20 -p "Choose Search") || exit 1

if [ "$choice" ]
then
    query=$(rofi -dmenu -i -l 20 -p "Query $choice") || exit 1
fi
engineurl=${options["$choice"]}

xdg-open "$engineurl""$query" &
