#!/usr/bin/env bash

# Install i3lock-color
sudo apt update && sudo apt upgrade -y
sudo apt install autoconf gcc make pkg-config libpam0g-dev libcairo2-dev libfontconfig1-dev libxcb-composite0-dev libev-dev libx11-xcb-dev libxcb-xkb-dev libxcb-xinerama0-dev libxcb-randr0-dev libxcb-image0-dev libxcb-util-dev libxcb-xrm-dev libxkbcommon-dev libxkbcommon-x11-dev libjpeg-dev
mkdir ~/Builds
git clone https://github.com/Raymo111/i3lock-color.git ~/Builds/i3lock-color
cd ~/Builds/i3lock-color && git pull
git tag -f "git-$(git rev-parse --short HEAD)"
./install-i3lock-color.sh 

#Install betterlockscreen
sudo apt install feh
git clone https://github.com/betterlockscreen/betterlockscreen.git ~/Builds/betterlockscreen
cd ~/Builds/betterlockscreen && git pull
sudo ./install.sh system 
