#!/bin/sh

sudo apt install libnotify-bin libnotify-dev
mkdir ~/Builds
git clone https://github.com/dunst-project/dunst.git ~/Builds/dunst
cd ~/Builds/dunst
make dunstify
sudo cp dunstify /usr/local/bin/
rm -rf ~/Builds/dunst
