#!/bin/sh
mkdir ~/Builds
git clone https://github.com/eclipse/eclipse.jdt.ls.git ~/Builds/eclipse.jdt.ls
cd ~/Builds/eclipse.jdt.ls && git pull
export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
./mvnw clean install -DskipTests
