#!/bin/sh

install_rustup(){ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh; }

sudo apt update && sudo apt upgrade -y
sudo apt install -y curl \
    gnupg ca-certificates git \
    gcc-multilib g++-multilib cmake libssl-dev pkg-config \
    libfreetype6-dev libasound2-dev libexpat1-dev libxcb-composite0-dev \
    libbz2-dev libsndio-dev freeglut3-dev libxmu-dev libxi-dev libfontconfig1-dev
mkdir ~/Builds
git clone "https://github.com/Kethku/neovide" ~/Builds/neovide
cd ~/Builds/neovide && git pull
rustup update || install_rustup
cargo build --release
sudo cp target/release/neovide /usr/local/bin
