#!/bin/sh
sudo apt update && sudo apt upgrade -y
sudo apt install libexif-dev libxft-dev libxft2 libimlib2 libimlib2-dev
mkdir ~/Builds
git clone https://github.com/nsxiv/nsxiv.git ~/Builds/nsxiv
cd ~/Builds/nsxiv 
make
sudo make install-all
