#!/bin/sh
sudo apt update && sudo apt upgrade -y
sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl
mkdir ~/Builds
git clone https://github.com/neovim/neovim ~/Builds/neovim 
cd ~/Builds/neovim && git pull
make -j4
sudo make install

